### ISSUE TITLE
dissector cannot upload using the user "ddosdb"

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/dddosdb-in-a-box#2]
It seems that user ddosdb has no right to upload fingerprints on the repository. The user "upload" might work however, the credentials are not documented.

**Comment by poorting** [comment]
ddosdb is the Django superuser, with it you can add other users that can upload. The default password for the upload user is 'uploadupload' :-)
(But user upload cannot access the admin pages)
